In [2]:
import pandas
import folium

In [3]:
import pandas as pd
data = pd.read_csv('hospital_tg.csv', encoding='latin1')
data.sample(5)

,PAYS,VILLE,TYPE DE PARTENAIRE,NOM DU PARTENAIRE,SPECIALITE,TELEPHONE,E-MAIL,Latitude,Longitude,QUARTIER,ADRESSE
65,TOGO,LOME,CLINIQUE,CLINIQUE OPHTALMOLOGIQUE LUMIERE DIVINE (C.O.L.D),OPHTALMOLOGIE,22257898 ; 93398702 / 91587858,ophtacold@gmail.com;emwod@hotmail.com,6.187188,1.192937,"Lomé, Totsi",3269 Av Pya
31,TOGO,KARA,HOPITAL,CHR KARA TOMDE,"MEDECINE GENERALE, GYNECOLOGIE OBSTETRIQUE, CH...",26 60 02 50,chrkaratomde@gmail.com,9.561687,1.202438,Kara Kara,Kara
36,TOGO,LOME,CLINIQUE,CLINIQUE ALPIA,"MEDECINE GENERALE, GYNECOLOGIE OBSTETRIQUE, AN...",22 21 63 95 ; 90 11 48 80,alpia_24@yahoo.fr,6.138687,1.220813,Lome Lome,Lome
4,TOGO,LOME,CABINET,CABINET CARDIO 24 (ENAM),CARDIOLOGIE,22 22 44 97/ 92 25 00 25,docesse@yahoo.fr,6.135063,1.213688,Lome Hanoukopé,Hanoukopé
97,TOGO,SOKODE,CLINIQUE,POLYCLINIQUE SOKODE,"MEDECINE GENERALE, GYNECOLOGIE OBSTETRIQUE, AN...",90 12 45 16/ 25 50 12 57,jackak310@yahoo.fr,8.981687,1.139312,Sokode Sokode,Sokode

In [4]:
data.dtypes

PAYS                      str
VILLE                     str
TYPE DE PARTENAIRE        str
NOM DU PARTENAIRE         str
SPECIALITE                str
TELEPHONE                 str
E-MAIL                    str
Latitude              float64
Longitude             float64
QUARTIER                  str
ADRESSE                   str
dtype: object

In [5]:
data.drop(['PAYS','E-MAIL','TYPE DE PARTENAIRE', 'TELEPHONE','ADRESSE'], axis=1, inplace=True)
data.sample(5)

,VILLE,NOM DU PARTENAIRE,SPECIALITE,Latitude,Longitude,QUARTIER
8,LOME,CABINET DENTAIRE PDG,CHIRURGIE DENTAIRE,6.133687,1.236063,Lome Lome
71,LOME,CLINIQUE SANTE POUR TOUS,"MEDECINE GENERALE, GYNECOLOGIE OBSTETRIQUE, AN...",6.196813,1.240563,Lome Kegue
26,ATAKPAME,CENTRE HOSPITALISER REGIONAL (CHR) ATAKPAME,"MEDECINE GENERALE, GYNECOLOGIE OBSTETRIQUE, CH...",7.532563,1.126313,Atakpame Atakpame
16,LOME,CABINET MEDICAL SAINT MICHEL,"MEDECINE GENERALE, PEDIATRIE, DERMATOLOGIE, OR...",6.167937,1.202063,Lome Attikoumé
66,LOME,CLINIQUE PERPETUEL SECOURS,"MEDECINE GENERALE, GYNECOLOGIE OBSTETRIQUE, CH...",6.181188,1.197313,"Lome Lomé, Djidjolé, Rue 123 face CEG LA SAGESSE"

In [6]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   VILLE              118 non-null    str
 1   NOM DU PARTENAIRE  118 non-null    str
 2   SPECIALITE         118 non-null    str
 3   Latitude           118 non-null    float64
 4   Longitude          118 non-null    float64
 5   QUARTIER           118 non-null    str
dtypes: float64(2), str(4)
memory usage: 5.7 KB

In [ ]:
data.describe()
#juste pour verifier s il n y a pas des coordonnees or du togo

         Latitude   Longitude
count  118.000000  118.000000
mean     6.749382    1.154378
std      1.199061    0.199603
min      6.125687    0.204187
25%      6.149906    1.181688
50%      6.188562    1.205188
75%      6.325750    1.223188
max     10.871187    1.581438

In [9]:
data.describe(include='object')

/tmp/ipykernel_52558/3382516499.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  data.describe(include='object')

,VILLE,NOM DU PARTENAIRE,SPECIALITE,QUARTIER
count,118,118,118,118
unique,27,118,58,75
top,LOME,CENTRE HOSPITALIER REGIONAL (CHR) LOME COMMUNE,OPTIQUE,Lome Lome
freq,87,1,14,38

In [10]:
city_counts = data['VILLE'].value_counts()
city_counts

VILLE
LOME                        87
KARA                         4
SOKODE                       3
KPALIME                      1
ANEHO                        1
BASSAR                       1
BLITTA                       1
VOGAN                        1
TSEVIE                       1
ATAKPAME                     1
SOTOUBOUA                    1
DAPAONG                      1
ADJENGRE - SOTOUBOUA         1
AHEPE                        1
ASSAHOUN                     1
NOTSE                        1
ADANGBE                      1
AOUDA - SOTOUBOUA            1
BAPURE - GUERIN KOUKA        1
KATCHAMBA - GUERIN KOUKA     1
KIDJABOUN - GUERIN KOUKA     1
KPATCHILE - GUERIN KOUKA     1
NANDOUTA - GUERIN KOUKA      1
NAWARE - GUERIN KOUKA        1
TCHEBEBE - SOTOUBOUA         1
TCHEKPO D                    1
ZAFI                         1
Name: count, dtype: int64

In [12]:
mean_latitude = data['Latitude'].mean()
mean_longitude = data['Longitude'].mean()
m = folium.Map(location=[mean_latitude, mean_longitude], zoom_start=12)
display(m)